[build]
  publish = "public"
  command = "npm run build"

[[redirects]]
  from = "/about"
  to = "/"
[[redirects]]
  from = "/portfolio"
  to = "/projects.html"
[[redirects]]
  from = "/projects"
  to = "/projects.html"
[[redirects]]
  from = "/contact"
  to = "/contact.html"
[[redirects]]
  from = "/resume"
  to = "/resume.html"
[[redirects]]
  from = "/blog"
  to = "/blog/"
[[redirects]]
  from = "/map/barrie"
  to = "/blog/barrie-transit-map.html"
